export default [
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/SOLANA%20Volume%20Bot%20on%20Telegram.png?updatedAt=1735771535130",
    status: true,
    price: "400",
    youtube: "",
    slug: "solana-volume-bot-telegram",
    category: "telegram bots",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/pumpfun-clone.png?updatedAt=1727082514946",
    status: true,
    price: "300",
    youtube: "",
    slug: "pump-fun-clone-development",
    category: "dapps",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/Dark%20Blue%20Red%20White%20Generic%20News%20General%20News%20YouTube%20Banner.png?updatedAt=1724719432697",
    status: true,
    price: "300",
    youtube: "jnL-70RXVII",
    slug: "telegram-mini-app",
    category: "telegram bots",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/Copy%20of%20Black%20and%20Yellow%20Dark%20Gamer%20Survival%20YouTube%20Banner.png?updatedAt=1724719521891",
    status: true,
    price: "500",
    youtube: "M98xybTnuoY",
    slug: "pinksale-launchpad-clone",
    category: "dapps",
  },
  {
    image: "",
    status: true,
    price: "600",
    youtube: "",
    slug: "solana-casino-platform",
    category: "dapps",
  },
  {
    image: "",
    status: true,
    price: "600",
    youtube: "",
    slug: "telegram-sniper-bot-clone",
    category: "telegram bots",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/Layer%202%20blockchain%20(1).png?updatedAt=1724719658061",
    status: true,
    price: "1500",
    youtube: "Ynn_hBBORUY",
    slug: "pos-blockchain-development",
    category: "blockchain",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/Layer%202%20blockchain%20(1).png?updatedAt=1724719658061",
    status: true,
    price: "1500",
    youtube: "Ynn_hBBORUY",
    slug: "poa-blockchain-development",
    category: "blockchain",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/Layer%202%20blockchain%20(1).png?updatedAt=1724719658061",
    status: true,
    price: "500",
    youtube: "Ynn_hBBORUY",
    slug: "testnet-evm-blockchain-development",
    category: "blockchain",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/create%20crypto%20gamble%20games%20website%20with%20blackjack%20dice%20crash.png?updatedAt=1724719749080",
    status: true,
    price: "1000",
    youtube: "E4fIL4SjEXk",
    slug: "cryptocurrency-casino-development",
    category: "dapps",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/CEX.png?updatedAt=1724719582998",
    status: true,
    price: "2000",
    youtube: "",
    slug: "centralized-crypto-exchange-development",
    category: "exchange",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/polywrap-uniswap-demo.png?updatedAt=1745273698271",
    status: true,
    price: "1500",
    youtube: "",
    slug: "decentralized-crypto-exchange-development",
    category: "exchange",
  },
  {
    image: "",
    status: true,
    price: "100",
    youtube: "",
    slug: "token-development",
    category: "token",
  },
  {
    image: "",
    status: true,
    price: "1000",
    youtube: "",
    slug: "nft-marketplace-development",
    category: "nft",
  },
  {
    image: "",
    status: true,
    price: "500",
    youtube: "",
    slug: "nft-minting-website-development",
    category: "nft",
  },
  {
    image: "",
    status: true,
    price: "1000",
    youtube: "",
    slug: "white-label-crypto-wallet-development",
    category: "wallet",
  },
  {
    image:
      "https://ik.imagekit.io/hp2oyifpf/polywrap-uniswap-demo.png?updatedAt=1745273698271",
    status: true,
    price: "400",
    youtube: "",
    slug: "amm-dex-uniswap-clone",
    category: "exchange",
  },
  {
    image: "",
    status: true,
    price: "100",
    youtube: "",
    slug: "fix-walletconnect-relay-error",
    category: "dapps",
  },
  {
    image: "",
    status: true,
    price: "1000",
    youtube: "",
    slug: "ai-cryptocurrency-application-development",
    category: "ai",
  },
];
